spring:
  application:
    name: monitoring
  datasource:
    url: jdbc:postgresql://0.0.0.0:5432/postgres
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database: postgresql
  profiles:
    active: development

# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
