services:
  timescaledb2:
    image: timescale/timescaledb-ha:pg16
    container_name: timescaledb2
    ports:
      - 5416:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks: 
      - monitoring-network

  backend:
    depends_on:
      timescaledb2:
        condition: service_healthy
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    ports:
      - 8081:8080
    networks: 
      - monitoring-network

  front_server:
    depends_on:
      timescaledb2:
        condition: service_healthy
    build:
      context: ./src/main/webclient
      dockerfile: Dockerfile
    user: 1000:1000
    environment:
      NODE_ENV: production
    volumes:
      - ./src/main/webclient/build:/usr/share/nginx/html
      # - ./nginx/ssl:/etc/nginx/ssl
    ports:
      - 443:443
    networks: 
      - monitoring-network

networks:
  monitoring-network:
