version: "v2.26.1-desktop.1"

services:
   front-end:
     build: ./src/main/webclient
     ports:
       - 3000:3000


  timescaledb2:
    image: timescale/timescaledb-ha:pg16
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=timescaledb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin