spring:
  application:
    name: monitoring
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database: postgresql
  profiles:
    active: development
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-5neb7art3ltrcarr.us.auth0.com/
          jwk-set-uri: https://dev-5neb7art3ltrcarr.us.auth0.com/.well-known/jwks.json
          jws-algorithms: RS256

# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
