name: Deploy to Heroku

on:
  push:
    branches:
      - battery

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    environment: heroku
    steps:
      - uses: actions/checkout@v3
      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
      - name: Deploy backend to Heroku
        uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "errwarn"
          heroku_email: ${{ secrets.EMAIL }}
          usedocker: true
          docker_heroku_process_type: "web"
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

  deploy-frontend:
    runs-on: ubuntu-latest
    environment: heroku
    steps:
      - uses: actions/checkout@v3
      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
      - name: Deploy frontend to Heroku
        uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "frontend-errwarn"
          heroku_email: ${{ secrets.EMAIL }}
          usedocker: true
          docker_heroku_process_type: "web"
          appdir: "src/main/webclient"
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
